[book]
authors = ["Lars"]
language = "en"
src = "src"
title = "VerCors Tutorial"

[output.html]
default-theme = "vercors"
site-url = "https://vercors.ewi.utwente.nl/wiki"

[output.html.playground]
editable = true
copyable = true
line-numbers = true